// ================================================
// MOCK DATA FOR LOCAL DEVELOPMENT
// ================================================
// This file provides mock data when Supabase is not available

export const mockRooms = [
  // Standard Rooms
  {
    id: '1',
    room_number: 'S-101',
    room_type: 'standard',
    building: 'main',
    capacity: 2,
    price_per_night: 250,
    status: 'available',
    amenities: ['AC', 'WiFi', 'TV', 'Bathroom'],
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    room_number: 'S-102',
    room_type: 'standard',
    building: 'main',
    capacity: 2,
    price_per_night: 250,
    status: 'available',
    amenities: ['AC', 'WiFi', 'TV', 'Bathroom'],
    created_at: new Date().toISOString(),
  },
  // Executive Rooms
  {
    id: '3',
    room_number: 'E-201',
    room_type: 'executive',
    building: 'main',
    capacity: 3,
    price_per_night: 350,
    status: 'available',
    amenities: ['AC', 'WiFi', 'TV', 'Bathroom', 'Mini Bar', 'Bathrobe'],
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    room_number: 'E-202',
    room_type: 'executive',
    building: 'main',
    capacity: 3,
    price_per_night: 350,
    status: 'occupied',
    amenities: ['AC', 'WiFi', 'TV', 'Bathroom', 'Mini Bar', 'Bathrobe'],
    created_at: new Date().toISOString(),
  },
  // Presidential Suites
  {
    id: '5',
    room_number: 'P-301',
    room_type: 'presidential',
    building: 'main',
    capacity: 4,
    price_per_night: 500,
    status: 'available',
    amenities: ['AC', 'WiFi', 'TV', 'Bathroom', 'Mini Bar', 'Bathrobe', 'Jacuzzi'],
    created_at: new Date().toISOString(),
  },
  // Chalets
  {
    id: '6',
    room_number: 'C-401',
    room_type: 'chalet',
    building: 'chalet',
    capacity: 4,
    price_per_night: 450,
    status: 'available',
    amenities: ['AC', 'Kitchen', 'WiFi', 'TV', 'Bathroom'],
    created_at: new Date().toISOString(),
  },
];

export const mockBookings = [
  {
    id: '1',
    room_id: '2',
    guest_name: 'John Doe',
    guest_email: 'john@example.com',
    guest_phone: '0201234567',
    check_in_date: '2026-02-05',
    check_out_date: '2026-02-07',
    total_nights: 2,
    base_price: 500,
    tour_addon_price: 0,
    discount_amount: 0,
    total_amount: 500,
    payment_status: 'completed',
    status: 'confirmed',
    booking_reference: 'WGH-20260201-001',
    created_at: new Date().toISOString(),
  },
];

export const mockAdminUser = {
  id: '1',
  email: 'admin@winnersgoldhotel.com',
  password: 'Demo@123456', // In real app, this is hashed
  full_name: 'Admin User',
  role: 'admin',
  status: 'active',
};

export const mockTours = [
  {
    id: 1,
    name: 'Kintampo Falls',
    description: 'Experience the beauty of Kintampo Falls with guided tours',
    distance: '35 km',
    duration: '4 hours',
    price: 50,
  },
  {
    id: 2,
    name: 'Boabeng-Fiema Wildlife',
    description: 'See monkeys and wildlife in their natural habitat',
    distance: '45 km',
    duration: '5 hours',
    price: 60,
  },
  {
    id: 3,
    name: 'Tano Boase Grove',
    description: 'Visit the sacred grove with rich cultural heritage',
    distance: '20 km',
    duration: '3 hours',
    price: 35,
  },
  {
    id: 4,
    name: 'Bono Manso Historical',
    description: 'Learn about Bono kingdom history and culture',
    distance: '25 km',
    duration: '3.5 hours',
    price: 40,
  },
];

export const mockDiscountCodes = [
  {
    id: '1',
    code: 'WELCOME10',
    description: '10% off for new guests',
    discount_percent: 10,
    discount_amount: null,
    valid_from: '2026-01-01',
    valid_until: '2026-12-31',
    max_uses: 100,
    current_uses: 15,
    min_booking_amount: 100,
    is_active: true,
  },
  {
    id: '2',
    code: 'GROUP20',
    description: '20% off for group bookings',
    discount_percent: 20,
    discount_amount: null,
    valid_from: '2026-01-01',
    valid_until: '2026-12-31',
    max_uses: 50,
    current_uses: 5,
    min_booking_amount: 1000,
    is_active: true,
  },
];

// Mock Conference Bookings
export const mockConferenceBookings = [
  {
    id: 'conf-1',
    contact_name: 'Dr. Kwame Mensah',
    contact_email: 'kmensah@businessgh.com',
    contact_phone: '+233 24 555 1234',
    organization: 'Ghana Business Association',
    event_type: 'Annual General Meeting',
    booking_date: '2026-02-15',
    start_time: '09:00',
    end_time: '17:00',
    duration_hours: 8,
    expected_attendees: 120,
    package_type: 'full_day',
    base_price: 600,
    catering_cost: 1800,
    total_amount: 2400,
    requires_projector: true,
    requires_catering: true,
    special_requirements: 'Need microphones for panel discussions. Parking for 30 vehicles.',
    payment_status: 'completed',
    payment_method: 'bank_transfer',
    status: 'confirmed',
    booking_reference: 'CONF702856XYZ123',
    created_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'conf-2',
    contact_name: 'Rev. Sarah Owusu',
    contact_email: 'sarah.owusu@techimanchurch.org',
    contact_phone: '+233 20 123 4567',
    organization: 'Techiman Community Church',
    event_type: 'Leadership Workshop',
    booking_date: '2026-02-08',
    start_time: '14:00',
    end_time: '18:00',
    duration_hours: 4,
    expected_attendees: 50,
    package_type: 'half_day',
    base_price: 400,
    catering_cost: 0,
    total_amount: 400,
    requires_projector: true,
    requires_catering: false,
    special_requirements: 'Need sound system for hymns and presentations.',
    payment_status: 'pending',
    payment_method: 'mtn_momo',
    status: 'confirmed',
    booking_reference: 'CONF702857ABC456',
    created_at: new Date('2026-01-28').toISOString(),
  },
];
